server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/takasdb
    username: postgres
    password: fatih123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
